const mockNullData = {
  ident: 'mockIdent',
  createdAt: '2020',
  updatedAt: '2020',
  authorSignature: null,
  authorSignedAt: null,
  reviewerSignature: null,
  reviewerSignedAt: null,
};

const mockNullObjectData = {
  ident: 'mockIdent',
  createdAt: '2020',
  updatedAt: '2020',
  authorSignature: null,
  authorSignedAt: null,
  reviewerSignature: {
    ident: null,
    createdAt: null,
    updatedAt: null,
    email: null,
    firstName: null,
    lastName: null,
    lastLogin: null,
    type: null,
    username: null,
  },
  reviewerSignedAt: null,
};

const mockObjectData = {
  ident: 'mockIdent',
  createdAt: '2020',
  updatedAt: '2020',
  authorSignature: null,
  authorSignedAt: null,
  reviewerSignature: {
    ident: '0000-1111',
    createdAt: '2020',
    updatedAt: '2020',
    email: 'aaa@bcgsc.ca',
    firstName: 'eeee',
    lastName: 'ooooo',
    lastLogin: null,
    type: 'bcgsc',
    username: 'eooooo',
  },
  reviewerSignedAt: '2020',
};

const mockReportData = {
  ident: 'mockIdent',
  createdAt: '2020',
  updatedAt: '2020',
  alternateIdentifier: null,
  pediatricIds: null,
  analysisStartedAt: null,
  biopsyName: null,
  createdBy: null,
  expression_matrix: null,
  kbVersion: null,
  patientId: null,
  patientInformation: null,
  ploidy: null,
  projects: null,
  reportVersion: null,
  sampleInfo: null,
  state: null,
  subtyping: null,
  template: null,
  tumourContent: null,
  type: null,
  users: null,
  oncotreeTumourType: null,
  kbDiseaseMatch: null,
  m1m2Score: null,
  captiv8Score: null,
  appendix: null,
};

export {
  mockNullData,
  mockNullObjectData,
  mockObjectData,
  mockReportData,
};
