const app = angular.module('bcgscIPR', [
  'templates',
  'ngMaterial',
  'ngSanitize',
  'ui.router',
  'angularMoment',
  'ngStorage',
  'angularFileUpload',
  'angular-sortable-view',
  'ngQuill',
  'chart.js',
  'btford.socket-io',
  'angular-async-await',
  'ngMessages',
]);
