name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    name: node-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: coverage/junit.xml
        if: matrix.node == 12
      - uses: codecov/codecov-action@v1
        with:
          yml: codecov.yml
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.node == 12
  docker:
    runs-on: ubuntu-latest
    name: docker-build
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build --file Dockerfile --tag pori/ipr-client .
