import React, {
  useEffect, useState, useRef, useMemo, useCallback,
} from 'react';
import { UncontrolledReactSVGPanZoom } from 'react-svg-pan-zoom';
import InlineSVG from 'react-inlinesvg';
import AutoSizer from 'react-virtualized-auto-sizer';

import './index.scss';

type SvgImageProps = {
  image: string;
  isPrint?: boolean;
  printOrientation?: 'portrait' | 'landscape' | 'auto';
  /** Fires once the SVG has been parsed and rendered to the DOM. */
  onLoad?: () => void;
  /**
   * On-screen only: size the pan/zoom viewer to its (square) container and fit the
   * whole SVG into it, instead of using the SVG's intrinsic height (which overflows
   * a fixed-size preview box). Leave false to keep the intrinsic-height behaviour.
   */
  fitToContainer?: boolean;
};

// These should be same as index.css under @page
// Accounts for padding via magical numbers 32 and 16
const INCH_TO_PX = 96;
const MAX_PRINT_WIDTH = Math.floor((9 - 0.4 * 2) * INCH_TO_PX) - 32;
const MAX_PRINT_HEIGHT = Math.floor((11.5 - 0.4 * 2) * INCH_TO_PX) - 64;

const PRINT_WIDTH = 816;
const ICON_WIDTH = 48;

const SvgImage = ({
  image,
  isPrint = false,
  // Only applicable when in print mode
  printOrientation = 'portrait',
  onLoad,
  fitToContainer = false,
}: SvgImageProps): JSX.Element => {
  const Viewer = useRef(null);
  const [svgHeight, setSvgHeight] = useState<number>();
  const [svgWidth, setSvgWidth] = useState<number>();
  const [processedImage, setProcessedImage] = useState('');
  useEffect(() => {
    if (processedImage) {
      const svg = new DOMParser().parseFromString(processedImage, 'image/svg+xml');
      const [svgElem] = svg.getElementsByTagName('svg');
      setSvgHeight(svgElem?.height?.baseVal?.value || PRINT_WIDTH);
      setSvgWidth(svgElem?.width?.baseVal?.value || PRINT_WIDTH);
    }
  }, [processedImage]);

  useEffect(() => {
    if (image) {
      const replacer = (matched: string) => {
        const prop = matched.match(/(?<=")[^:]+/);
        const val = matched.match(/(?<=:\s*)[^\s][^;]+/);
        return `${prop}="${val}"`;
      };
      /* This handles SVGs generated by Abobe Illustrator */
      /* Regex finds style="prop: value" in the svg tag and replaces with the attr prop="value" */
      const styled = image.replace(
        /(?<=<svg[^>]*?)style=((\\?"[^"]*?\\?")|(\\?'[^']*?\\?'))/g,
        replacer,
      );

      /*
        Adobe Illustrator exports frequently set width/height but omit viewBox.
        Without a viewBox the SVG does not scale when resized for print — it clips
        to the smaller viewport instead of shrinking the artwork. Derive a viewBox
        from the width/height so the whole image scales to fit.
      */
      let finalImage = styled;
      const [svgElem] = new DOMParser()
        .parseFromString(styled, 'image/svg+xml')
        .getElementsByTagName('svg');
      const width = svgElem?.width?.baseVal?.value;
      const height = svgElem?.height?.baseVal?.value;
      if (svgElem && !svgElem.getAttribute('viewBox') && width && height) {
        svgElem.setAttribute('viewBox', `0 0 ${width} ${height}`);
        finalImage = new XMLSerializer().serializeToString(svgElem);
      }

      setProcessedImage(finalImage);
    }
    return () => setProcessedImage('');
  }, [image]);

  const handleFit = useCallback(() => {
    Viewer?.current?.fitToViewer();
  }, []);

  const svgComponent = useMemo(() => {
    if (processedImage && svgHeight && svgWidth) {
      /*
        Print is rendered outside of AutoSizer on purpose. The print scale is derived
        entirely from the SVG's own dimensions and the MAX_PRINT_* constants, so there
        is no width to measure here. Inside AutoSizer it also could not work: paged.js
        re-parents the live #root while paginating, so AutoSizer measured `.svg-image`
        as 0 wide and then skipped calling its children altogether, rendering nothing.
      */
      if (isPrint) {
        let overHeightRatio;
        let overWidthRatio;

        switch (printOrientation) {
          case 'landscape':
            overHeightRatio = svgHeight / MAX_PRINT_WIDTH;
            overWidthRatio = svgWidth / MAX_PRINT_HEIGHT;
            break;
          case 'auto':
            if (svgWidth > svgHeight) {
              overHeightRatio = svgHeight / MAX_PRINT_WIDTH;
              overWidthRatio = svgWidth / MAX_PRINT_HEIGHT;
            } else {
              overHeightRatio = svgHeight / MAX_PRINT_HEIGHT;
              overWidthRatio = svgWidth / MAX_PRINT_WIDTH;
            }
            break;
          default:
            // portrait
            overHeightRatio = svgHeight / MAX_PRINT_HEIGHT;
            overWidthRatio = svgWidth / MAX_PRINT_WIDTH;
            break;
        }

        let nextRatio = 1;

        if (overHeightRatio > 1 && overWidthRatio > 1) {
          // Both over, find higher ratio
          nextRatio = Math.max(overHeightRatio, overWidthRatio);
        } else if (overHeightRatio > 1) {
          nextRatio = overHeightRatio;
        } else if (overWidthRatio > 1) {
          nextRatio = overWidthRatio;
        }

        let transformCss = '';

        if (
          printOrientation === 'landscape'
          || (printOrientation === 'auto' && svgWidth > svgHeight)
        ) {
          transformCss = `rotate(90) translate(0 -${svgHeight * nextRatio})`;
        }
        return (
          <InlineSVG
            src={processedImage}
            height={svgHeight}
            width={svgWidth}
            transform-origin="top left"
            transform={`
              scale(${1 / nextRatio})
              ${transformCss}
            `}
            onLoad={onLoad}
          />
        );
      }

      return (
        <AutoSizer disableHeight onResize={handleFit}>
          {({ width }) => (
            <UncontrolledReactSVGPanZoom
              ref={Viewer}
              width={width}
              height={fitToContainer ? width : svgHeight}
              background="#FFFFFF"
              detectAutoPan={false}
              defaultTool="auto"
              customMiniature={() => null}
              customToolbar={undefined}
              toolbarProps={{ position: 'left' }}
            >
              <svg
                width={svgWidth}
                height={svgHeight}
              >
                <InlineSVG src={processedImage} onLoad={onLoad} />
              </svg>
            </UncontrolledReactSVGPanZoom>
          )}
        </AutoSizer>
      );
    }
    return null;
  }, [isPrint, printOrientation, processedImage, svgHeight, svgWidth, handleFit, onLoad, fitToContainer]);

  return (
    <div className="svg-image">
      {svgComponent}
    </div>
  );
};

export default SvgImage;
